# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_age', models.IntegerField(default=2)),
                ('c_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_age', models.IntegerField(default=2)),
                ('d_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
