# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('u_icon', models.ImageField(upload_to='icon')),
            ],
            options={
                'verbose_name': 'UserModel',
                'verbose_name_plural': 'UserModels',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
