# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uploadFiles', '0002_auto_20200504_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_icon',
            field=models.ImageField(upload_to='icons/%Y-%m'),
        ),
    ]
