# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oneToOne', '0004_auto_20200420_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(99), to='app_oneToOne.Person'),
        ),
    ]
