# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_oneToOne', '0005_auto_20200426_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_oneToOne.Person'),
        ),
    ]
